#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:0
#SBATCH --job-name=MultiAgentFairness
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/repos/multiagent_fairness_reproducibility
#xvfb-run -a python baselines/baselines.py --mode test --render
xvfb-run -a python eval/collect_actions.py --env simple_torus --pred_policy greedy --prey_policy random --seed 75  
python main.py --env simple_torus --algorithm ddpg_speed_fair --collaborative True


python eval/collect_actions.py --env simple_torus --pred_policy ddpg --prey_policy cosine --seed 72 --pred_vel 1.1 --checkpoint_path results\ddpg_symmetric_simple_torus\ddpg_symmetric_collab_01_18_2023__12_02_00 